name: ssm-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipython
  - numpy
  - matplotlib-base
  - matplotlib-inline
  - cmocean
  - scipy
  - sqlite
  - adjusttext
  - contextily
  - sqlalchemy[version='<2']
  - psycopg2
  - scikit-learn
  - psutil
  - jupyter_client
  - ipykernel
  - pandas
  - rtree
  - openpyxl
  - netcdf4
  - geopandas
  - shapely
  - networkx
  - joblib
prefix: /home/benr/mambaforge/envs/ssm-analysis
